name: first_flow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: | 
            echo "Hello, world!"
             echo "Why always world"
